CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(190) NOT NULL UNIQUE,
    active TINYINT(1) NOT NULL DEFAULT 1,
    score DECIMAL(12, 2),
    ratio DOUBLE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    metadata JSON,
    avatar BLOB,
    ucount BIGINT UNSIGNED NOT NULL DEFAULT 18446744073709551615
);

INSERT INTO users (id, email, active, score, ratio, created_at, metadata, avatar, ucount)
SELECT n,
       CONCAT('user-', n, '@example.test'),
       MOD(n, 3) <> 0,
       MOD(n, 10000) / 100,
       n / 7,
       TIMESTAMP('2024-01-01 00:00:00') + INTERVAL n SECOND,
       JSON_OBJECT('id', n, 'fixture', TRUE),
       UNHEX('010203'),
       18446744073709551615
FROM (
    SELECT ones.n + tens.n * 10 + hundreds.n * 100 + thousands.n * 1000 + ten_thousands.n * 10000 + 1 AS n
    FROM (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
    CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
    CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundreds
    CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) thousands
    CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ten_thousands
) fixture
WHERE n <= 25000;

ALTER TABLE users AUTO_INCREMENT = 25001;
CREATE VIEW active_users AS SELECT * FROM users WHERE active = 1;

CREATE TABLE notes (id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, body LONGTEXT NOT NULL);
INSERT INTO notes (body) VALUES (REPEAT('large-cell-', 3000));
